version: "3"
services:
    equimetre:
        container_name: equimetre
        build: ./
        ports:
            - 80:80
        volumes:
#            - /srv/http/Equiapi:/var/www/Equiapi:rw
#            - /srv/http/Equimetre:/var/www/Equimetre:rw
#
#            - ./apache2/httpd.conf:/etc/apache2/httpd.conf
#            - ./apache2/conf.d:/etc/apache2/conf.d
#            - ./apache2/sites.d:/etc/apache2/sites.d
            - ../:/var/www/equimetre
#            - ./conf:/etc/apache2
#            - ./conf/php7:/etc/php7


