
version: "3"

services:

  # database
  mariadb:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - database_data:/var/lib/mysql
    expose:
        - 3306

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - "mariadb:db"
    ports:
      - "8080:80"

# store database
volumes:
    database_data:
